flutternetwork/WiFiFlutter

- pubspec.yaml
Fix for Flutter v0.6.0, now integrating Dart 2 build (2.1.0-dev.0.0).
According to https://github.com/flutter/flutter/wiki/Changelog, "package and plugin authors should ensure their pubspec.yaml files include a Dart SDK constraint with an upper bound of <3.0.0"
> Set SDK max to <3.0.0

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
The function **findAndConnect** uses the function WifiManager.getScanResults().
getScanResults requires the location persmission, otherwise it returns an empty list.
See issue https://github.com/alternadom/WiFiFlutter/issues/29
> Add permission request to findAndConnect

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
Fix the argument name in removeWifiNetwork.
https://github.com/alternadom/WiFiFlutter/blob/6211431de4d2f8037a8e411ca17999200ae8ecc0/lib/wifi_iot.dart#L308-L318
https://github.com/alternadom/WiFiFlutter/blob/6211431de4d2f8037a8e411ca17999200ae8ecc0/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java#L654-L658
> Fix argument name for removeWifiNetwork

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
d6ee479 fixes the problem for ```connect```. Add the fix to ```findAndConnect```.
> Implements d6ee479 for findAndConnect

- ios/Classes/SwiftWifiIotPlugin.swift
This fixed a crash on unpacking ``getSSID()!``. When the WiFi network doesn't exist, ``error`` is nil so we need to check the ``getSSID()`` result for ``nil``.
> Fix for connect() call when the WiFi network doesn't exist

- lib/wifi_iot.dart
since it is not supported on iOS
Closes https://github.com/alternadom/WiFiFlutter/issues/33
> not calling `setEnable` in `connect` method for iOS platform

- ios/Classes/SwiftWifiIotPlugin.swift
- https://github.com/alternadom/WiFiFlutter/issues/94
- Crash app happened when user connect one wifi error, because wifi config network system
- I checked null for syntax `self`, crash happened when we call method self.getSSID(), but variable `self` null lead to crash.
> Fix crash join wifi [IOS Only]

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
- android/src/main/java/info/whitebyte/hotspotmanager/WifiApManager.java
- lib/wifi_iot.dart
showWritePermissionSettings, a method that starts the intent to achieve
MANAGE_WRITE_SETTINGS, was present in the plugin already from the beginning
in WifiApManager class but was not part of the API and therefore not usable
directly.
This MR publishes it so it can be effectively used by code that requires
such permissions (ie. configuration of AP on devices) without the need
to have double code.
Closes #111
> Publish showWritePermissionSettings as part of public API

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
multiple result to channel crashing the plugin and app. preventing it using boolean flag.
> [android] `connectTo`: sending result only once

- android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
Android P *does* allow for startScan call, just throttles how often it can be done per two-minute period. This removes a conditional that prevented startScan from being called at all on that version.
#138
Relevant docs:
https://developer.android.com/guide/topics/connectivity/wifi-scan#wifi-scan-permissions
> Call startScan on Android P and Higher

- README.md
- ios/Classes/SwiftWifiIotPlugin.swift
Using `NEHotspotNetwork.fetchCurrent` instead
Closes #142 #105 #75 #121
> refactor(ios): handle deprecation of `CNCopyCurrentNetworkInfo `

- ios/Classes/SwiftWifiIotPlugin.swift
This patch adresses issues 
https://github.com/alternadom/WiFiFlutter/issues/161
and
https://github.com/alternadom/WiFiFlutter/issues/105
It adds a callback function to getSSID, which will resolve the result.
This is since NEHotspotNetwork.fetchCurrent's completionHandler is escaping. As a result ssid will never be set.
> fix(ios): getSSID and getBSSID always returning null

- .gitignore
- README.md
- ios/Classes/SwiftWifiIotPlugin.swift
This uses the same approach as network_info_plus:
https://github.com/fluttercommunity/plus_plugins/blob/a1b18402790b65f4f23cbb5d6ed7bb248480a70e/packages/network_info_plus/network_info_plus/ios/Classes/FLTNetworkInfoPlusPlugin.m#L54
The functionality is split across 2 functions, so we could as well implement getIPv6 by calling getNetworkInterface with AF_INET6 instead of AF_INET
> feat(ios): getIP implemented

- packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
- packages/wifi_iot/ios/Classes/SwiftWifiIotPlugin.swift
- packages/wifi_iot/lib/wifi_iot.dart
Based on the idea in https://github.com/florian-guillemard/WiFiFlutter/pull/158.  
However, we do not try to get the BSSID on connection, it has to be provided by the user.
On Android, the user is explicitly asked to connect only the first time. Further reconnection can be done with no user interaction. This also filters networks with the same SSID but a different BSSID.
On iOS, does nothing.
Tested on Android 12 and iOS 15.  
I do not have a device to test the deprecated path in Android.
> feat: allow to specify the `bssid` for registering and connecting network

- README.md
- packages/wifi_scan/README.md
- packages/wifi_scan/ios/Classes/SwiftWifiScanPlugin.swift
- packages/wifi_scan/ios/wifi_scan.podspec
- packages/wifi_scan/lib/src/accesspoint.dart
- packages/wifi_scan/lib/src/can.dart
- packages/wifi_scan/lib/wifi_scan.dart
- packages/wifi_scan/pubspec.yaml
- updated "plugin description", to be >60 char, pub.dev requirement
- referring to iOS implementation as "stub" and not "dummy"
- reamde: line breaks wherever possible, before `[]()`
> docs(wifi_scan): improvement

- packages/wifi_iot/ios/Classes/SwiftWifiIotPlugin.swift
When calling connect function with iOS without providing password the app crashed because it was excepting value. 
Now  you can join open wifi networks also with iOS .
> fix: iOS accept connect function password argument to be nil

- packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
+ error log only when `networkCallback` and `networkSuggestions` both are null
> fix(wifi_iot,android): `disconnect` - returning result properly 

- packages/wifi_scan/README.md
- packages/wifi_scan/android/build.gradle
- packages/wifi_scan/android/src/main/kotlin/dev/flutternetwork/wifi/wifi_scan/WifiScanPlugin.kt
- packages/wifi_scan/example/android/app/src/main/AndroidManifest.xml
- packages/wifi_scan/example/android/build.gradle
- packages/wifi_scan/example/lib/main.dart
- packages/wifi_scan/ios/Classes/SwiftWifiScanPlugin.swift
- packages/wifi_scan/lib/src/error.dart
- packages/wifi_scan/lib/src/result.dart
- packages/wifi_scan/lib/wifi_scan.dart
- packages/wifi_scan/test/wifi_scan_test.dart
- instead `Result<ValueType, ErrorType>` is added and used as return type
- example app simplified
- Kotlin upgrade
> refactor(wifi_scan)!: not having separate "can" APIs for checks

- packages/wifi_iot/README.md
- packages/wifi_iot/lib/wifi_iot.dart
- nudging to switch to `wifi_scan`
> docs(wifi_iot): deprecating message for "scan" related APIs

- packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
This is my proposed fix for issue #275
Changed the method `registerWifiNetworkDeprecated` to save found network id.  It it fails to both UPDATE or ADD a network it will return the registered network's id or fallback to -1;
This alone solved the issue of connecting to an already registered network. However during normal usage, if you tried to connect to a network using the wrong password, it would connect to it anyway, only to disconect with "Invalid Credentials" message in a few seconds.
In order to verify that the connection is actually taking place I changed the loop to watch for the [SupplicantState](https://developer.android.com/reference/android/net/wifi/SupplicantState) of the connection, and only break when some connection reaches "COMPLETED" status. 
Since this new check could …
> fix(wifi_iot): Fix connection to registered network on Android < 10 (Q)

- packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
This PR addresses #273 
Post SDK-31 (Android 11) the operating system supports concurrent connections. To address this Marichou created a fork of this repository and put a fix in place.
I've tidied the solution up and tested it against a Pixel 2 XL, Pixel 6a, and a Galaxy Tab A7 lite, and the solution works on all devices.
Also fixed a uses unchecked or unsafe operations warning.
> fix(wifi_iot): Add support for SDK-31 concurrent networks addresses #273

- packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
In Android 10, there is an issue where connection failures lead to repeated attempts to reconnect, resulting in the NetworkCallback being continuously triggered. However, within the context of Flutter, the FlutterResult allows only one return. To address this problem, it is recommended to unregister the NetworkCallback upon the first occurrence of the onUnavailable or onLost event, preventing subsequent redundant invocations. This pull request aims to implement this solution.
> fix: multiple triggering issue of NetworkCallback on Android 10

- packages/wifi_iot/ios/Classes/SwiftWifiIotPlugin.swift
Linked with this PR: https://github.com/flutternetwork/WiFiFlutter/pull/371
To resolve the branch merge issue.
> fix(wifi_iot): iOS isConnected always true even connection is failed - synced with master
