flutternetwork/WiFiFlutter

android/src/main/AndroidManifest.xml, android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, lib/wifi_iot.dart
Did a few changes including using eventChannel, it is currently able to return result. 
Limitation/known issue: not able to handle case if user rejects the request of permission but that should be fine for now.
=> fix scan result empty in Android

ios/Classes/SwiftWifiIotPlugin.swift
=> Added getBSSID implementation for iOS

ios/Classes/SwiftWifiIotPlugin.swift
getBSSID gad return value of type void
getBSSID was not passed into result() function
getBSSID was using undeclared variable
Sorry @alternadom for creating bugs in your code, it compiled correctly yesterday without any error messages.
=> iOS getBSSID fixes

android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
as #37 say, I have update the change here, so please merge it to main master. Thanks.
=> fix bug for client is reachable but not return client

README.md, ios/wifi_iot.podspec
* Fix iOS build by specifying Swift version in podspec file(#43)
* Improve readme with Xcode build informations about Swift static libraries
=> Add swift version on podspec config file

android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
Fixes https://github.com/alternadom/WiFiFlutter/issues/45
=> making plugin foreground only

android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, example/lib/main.dart
The example app is now a bit more clear for understanding how the plugin works.
=> Refractoring example app

README.md, pubspec.yaml
* Update link image for fixing display in pub.dev
* Add pub.dev link
* Add word to package description to bump it to more than 60 characters to please pub.dev
=> Update README.md and package description

.gitignore, CHANGELOG.md, android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, lib/wifi_iot.dart
Fix the force wifi method
Remove some verbose logs
=> [feature/fix_force_wifi] Fix the force wifi method

android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, lib/wifi_iot.dart
Closes #98, see discussion over there.
=> registerWifiNetwork:  saving with WiifiManager.addNetwork (API<=29) or ACTION_WIFI_ADD_NETWORKS (API>=30)

ios/Classes/SwiftWifiIotPlugin.swift
=> [iOS] ask for LocalNetwork permission in forceWifiUsage

CHANGELOG.md, example/pubspec.lock, example/pubspec.yaml, lib/wifi_iot.dart, pubspec.lock, pubspec.yaml
=> Null safety

README.md, android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, ios/Classes/SwiftWifiIotPlugin.swift
As no plan to implement it, anymore.
=> removed mac filtering (unimplemented methods)

android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java
Fix https://github.com/alternadom/WiFiFlutter/issues/167
Existing bug:  
When a permission needs to be requested (e.g. fine location to scan the wifi networks), we do not wait until the user has finished handling the request before making the API call, resulting in the call failing since the permission hasn't been granted yet.  
Once the permission had been granted, this issue would disappear.
Fix:
The result of the permission request is given in the [onRequestPermissionsResult] callback. Only call the API in this callback once the request has been answered by the user. The method success callback and required arguments are saved as field. Only one request can be handled at a time.  
When the permission is already granted, the previous call path is kept.  
The core functionality of the …
=> Gracefully handle permission requests

.github/workflows/all_plugins.yaml, melos.yaml, packages/wifi_iot/example/lib/main.dart, packages/wifi_iot/example/pubspec.yaml, packages/wifi_iot/lib/wifi_iot.dart
fix lint issues and remove exception for `wifi_iot` in melos `analyze` script
=> style(wifi_iot): as per anaylzer

packages/wifi_iot/lib/wifi_iot.dart
=> fix: proper serializing to avoid issue when obfuscated

packages/wifi_iot/lib/wifi_iot.dart
=> fix: `serializeNetworkSecurityMap` not mapping to null

packages/wifi_iot/lib/wifi_iot.dart
Check the SSID is valid according to IEEE Std 802.11. That is between 0 and 32 bytes.  
We also forbid 0 byte SSID since it has a special meaning and an AP cannot have a 0 length SSID.
On Android, trying to connect to an empty SSID returns the following fatal exception.  
E/AndroidRuntime( 6702): java.lang.IllegalStateException: cannot set match-none pattern for specifier  
E/AndroidRuntime( 6702): 	at android.net.wifi.WifiNetworkSpecifier$Builder.build(WifiNetworkSpecifier.java:422)  
E/AndroidRuntime( 6702): 	at com.alternadom.wifiiot.WifiIotPlugin.connectTo(WifiIotPlugin.java:1276)  
E/AndroidRuntime( 6702): 	at com.alternadom.wifiiot.WifiIotPlugin.access$200(WifiIotPlugin.java:50)  
E/AndroidRuntime( 6702): 	at com.alternadom.wifiiot.WifiIotPlugin$6.run(WifiIotPlugin.java:824)
=> fix: add size restrictions on the SSID according to IEEE Std 802.11

packages/wifi_iot/example/android/app/build.gradle, packages/wifi_iot/example/android/app/src/main/AndroidManifest.xml, packages/wifi_iot/example/android/app/src/main/res/values/styles.xml
Followed: https://github.com/flutter/flutter/wiki/Upgrading-pre-1.12-Android-projects
=> fix(wifi_iot_example): properly upgrade to v2 android embedding

.github/workflows/all_plugins.yaml, packages/wifi_scan/android/src/main/kotlin/dev/flutternetwork/wifi/wifi_scan/WifiScanPlugin.kt, packages/wifi_scan/pubspec.yaml
BREAKING CHANGE: dropped support for flutter v2 and below.
Fixes #280
=> fix(wifi_scan)!: flutter 3 support

packages/wifi_iot/android/src/main/java/com/alternadom/wifiiot/WifiIotPlugin.java, packages/wifi_iot/lib/wifi_iot.dart
=> feat(wifi_iot): Allows to change the default connection timeout from the application

.github/workflows/wifi_iot.yaml, .github/workflows/wifi_scan.yaml, packages/wifi_iot/.gitignore, packages/wifi_iot/android/build.gradle, packages/wifi_iot/android/gradle.properties, packages/wifi_iot/android/src/main/AndroidManifest.xml, packages/wifi_iot/example/android/app/build.gradle, packages/wifi_iot/example/android/app/src/main/AndroidManifest.xml, packages/wifi_iot/example/android/build.gradle, packages/wifi_iot/example/android/gradle.properties, packages/wifi_iot/example/android/gradle/wrapper/gradle-wrapper.properties, packages/wifi_scan/android/build.gradle, packages/wifi_scan/android/gradle.properties, packages/wifi_scan/android/gradle/wrapper/gradle-wrapper.properties, packages/wifi_scan/android/src/main/AndroidManifest.xml, packages/wifi_scan/example/android/app/build.gradle, packages/wifi_scan/example/android/app/src/main/AndroidManifest.xml, packages/wifi_scan/example/android/build.gradle, packages/wifi_scan/example/android/gradle.properties, packages/wifi_scan/example/android/gradle/wrapper/gradle-wrapper.properties
Please accept this pull request and release a new version of the library since it's blocking compilation with Flutter 3.16.
Thank you!
=> chore: Update Gradle to 8.2 and AGP to 8.2.0

packages/wifi_iot/android/build.gradle, packages/wifi_scan/android/build.gradle, packages/wifi_scan/example/lib/main.dart, pubspec.lock
=> fix: Update compileSdkVersion to fix Android release build with flutter 3.24
